language: python
python:
  - "3.8"

# upload manifests to S3
addons:
  artifacts:
    s3_region: "ap-southeast-2" # defaults to "us-east-1"
    paths: "output"
    target_paths: "generated"

# command to run tests
script:
  - pytest

# if tests are successful, generate the manifests
after_success:
  - python3 ./scripts/createManifest.py -outputFile=exampleManifest.json -inputFolder=examples
  - python3 ./scripts/createManifest.py -outputFile=manifest.json -inputFolder=alerts

