language: python
python:
- '3.8'

install:
  - pip install jsonschema
  
addons:
  ssh_known_hosts: firmware.ardupilot.org

script:
- pytest

after_success:
- python3 ./scripts/createManifest.py -outputFile=exampleManifest -inputFolder=examples
- python3 ./scripts/createManifest.py -outputFile=manifest -inputFolder=alerts
- python3 ./scripts/createManifest.py -format=js -outputFile=exampleManifest -inputFolder=examples
- python3 ./scripts/createManifest.py -format=js -outputFile=manifest -inputFolder=alerts

deploy:
  provider: script
  skip_cleanup: true
  script: rsync -avz -e "ssh -i useralerts" ./output/exampleManifest.json ./output/manifest.json ./output/exampleManifest.js ./output/manifest.js ./readers/alerts.html autotest@firmware.ardupilot.org:~/APM/buildlogs/binaries/userAlerts/
  on:
    branch: master

before_install:
- 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then openssl aes-256-cbc -K $encrypted_e9395dd1042c_key -iv $encrypted_e9395dd1042c_iv -in useralerts.enc -out ./useralerts -d; fi'
- 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then chmod 600 ./useralerts; fi'
